name: cogina_restaurants
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  fluttertoast: ^8.2.4
  flutter_verification_code: ^1.1.7
  flutter_screenutil: ^5.9.0
  easy_date_timeline: ^1.0.3
  easy_localization: ^3.0.5
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1 # #animation
  awesome_dialog: ^3.0.2 #dialog
  flutter_svg:  #svg images
  icons_plus: ^5.0.0
  cached_network_image:
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  flutter_local_notifications: ^9.5.3+1
  flutter_bloc: ^8.1.1
  device_preview: ^1.1.0
  image_picker: ^1.0.7
  dropdown_button2: ^2.3.9
  #location
  google_maps_flutter: ^2.5.1
  geolocator:
  geocoding:
  # DI
  get_it: ^7.2.0
  equatable: ^2.0.5

  # Local
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.15

  # Network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  connectivity_plus: ^3.0.2
  flutter_spinkit: ^5.1.0 #loading
  pin_code_fields: ^7.4.0
  webview_flutter: ^3.0.4
  country_code_picker: ^2.0.2
  file_picker: ^5.2.2
  stylish_bottom_bar: ^0.1.5
  smooth_page_indicator: ^1.0.0+2
  flutter_timer_countdown: ^1.0.5
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  audioplayers: ^5.2.1
  url_launcher: ^6.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/presentation/component/inputs/phone_country/flags/
    - assets/translation/
    - assets/mp3/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lateef-Light.ttf
          weight: 300
        - asset: assets/fonts/Lateef-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lateef-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lateef-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lateef-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lateef-ExtraBold.ttf
          weight: 800

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
