
default_platform(:android)

platform :android do
   desc "Push App Distribution to Firebase"
     lane :firebase_distribution do
#          sh "flutter clean"
#          sh "flutter build apk --release"
         firebase_app_distribution(
           app: "1:179875326250:android:da377b3d3f85ed9d049653",
           firebase_cli_token: "1//032zla4XJEwmqCgYIARAAGAMSNwF-L9Irk73OaBoveb7M9paAD2RDCK6U4IrCbZCNQEUfYv0pRM1GddbGE54X5dDS30KY8dZPj3c",
           android_artifact_type: "APK",
           android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
           testers: "eyehya576@gmail.com,pmmatrixclouds@gmail.com,safya.matrix21@gmail.com",
           release_notes: "🔥 Edit and handle add product with size and extar 🔥"
         )
     end
end
